apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delete-service
  template:
    metadata:
      labels:
        app: delete-service
    spec:
      containers:
        - name: delete-service
          imagePullPolicy: Never
          image: delete-service:latest
          ports:
            - containerPort: 5002
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 5002
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5002
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: student-management-config
                  key: MONGO_URI
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: student-management-config
                  key: DELETE_SERVICE_PORT

---
apiVersion: v1
kind: Service
metadata:
  name: delete-service
spec:
  selector:
    app: delete-service
  ports:
    - name: http
      protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 30002  
  type: NodePort
