apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          imagePullPolicy: Never
          image: search-service:latest
          ports:
            - containerPort: 5004
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 5004
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5004
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: student-management-config
                  key: MONGO_URI
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: student-management-config
                  key: SEARCH_SERVICE_PORT          

---
apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  selector:
    app: search-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 5004       
      targetPort: 5004  
      nodePort: 30004   
